language: erlang
otp_release:
  - 21.3
  - 20.0
  - 19.3

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - make test
  - make xref
  - make dialyzer
sudo: false
notifications:
  email:
    # recipients:
    #   - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
